version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
  build:
    commands:
      - echo "Building Docker image..."
      - docker tag $CONTAINER_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$CONTAINER_NAME:latest
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Image pushed to ECR successfully!"
      - echo "Deploying the Docker image to ECS..."
      - echo "Hello"
