version: 0.2

# Environment Variables (set these in CodeBuild project settings)
# - AWS_ACCOUNT_ID: Your AWS account ID
# - AWS_REGION: The AWS region for ECR and ECS
# - IMAGE_REPO_NAME: ECR repository name (e.g., "my-app")
# - IMAGE_TAG: Image tag (e.g., "latest" or a specific version)
# - ECS_CLUSTER_NAME: Name of your ECS cluster
# - ECS_SERVICE_NAME: Name of your ECS service

phases:
  pre_build:
    commands:
      - echo Restart docker...
      - echo "DOCKER_OPTS=\"--insecure-registry $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com\"" >> /etc/default/docker
      - service docker restart
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo Tagging the image...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Updating ECS service...
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment --container-image-detail name=$ECS_CONTAINER_NAME,image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
