version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Image pushed to ECR successfully!"
