version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/strapi-app # Or your desired directory
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user # Or your desired user
