version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u AWS -p $(aws ecr get-login--password-stdin --region $AWS_REGION) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg REVISION=$CODEBUILD_RESOLVED_SOURCE_VERSION --build-arg BUILD_NUMBER=$CODEBUILD_BUILD_ID -t $IMAGE_REPO_NAME:latest -f server/DockerfileAWS server/.
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
